name: deploy_to_firebase_hosting

on:
  push:
    tags:
      - release-production-*

jobs:
  deploy_to_firebase_hosting:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ 1//0gc2TjnCIOwtnCgYIARAAGBASNwF-L9Irvc-VE2nzJwSwoF8Q94F3FmfmUeHJJoV8oTwsUhLaUHGS-acl7_fFs5mWSHbs8tFuCBU }}
